openapi: 3.0.0
info:
  title: Service Registry GraphQL API
  description: GraphQL API for managing services in the Service Registry.
  version: 1.0.0
paths:
  /graphql:
    post:
      summary: GraphQL endpoint for service registry
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                variables:
                  type: object
      responses:
        "200":
          description: GraphQL response
components:
  schemas:
    Service:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        owner:
          type: string
  examples:
    listServicesQuery:
      value: |
        query {
          listServices {
            id
            name
            description
            owner
          }
        }
    createServiceMutation:
      value: |
        mutation createService($input: ServiceInput) {
          createService(input: $input) {
            id
            name
            description
            owner
          }
        }
