openapi: 3.0.0
info:
  title: Service Registry HTTP API
  description: HTTP API for CRUD operations on services in the Service Registry.
  version: 1.0.0
paths:
  /services:
    get:
      summary: List all services
      responses:
        "200":
          description: A list of services
    post:
      summary: Create a new service
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Service"
      responses:
        "201":
          description: Service created
  /services/{serviceId}:
    get:
      summary: Get service by ID
      parameters:
        - in: path
          name: serviceId
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Service details
    put:
      summary: Update service by ID
      parameters:
        - in: path
          name: serviceId
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Service"
      responses:
        "200":
          description: Service updated
    delete:
      summary: Delete service by ID
      parameters:
        - in: path
          name: serviceId
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Service deleted
components:
  schemas:
    Service:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        owner:
          type: string
